(() => {
 'use strict';
 const data=window.ART_CATALOG,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const media={game:'独立游戏',animation:'动画',comic:'漫画',film:'真人电影',creator:'插画与角色 IP'};
 const state={category:'all',medium:'all',usage:'all',query:'',award:false};let active=null,index=0,opener=null;
 const categoryName=id=>data.categories.find(c=>c.id===id)?.name||id;
 $('#total-works').textContent=data.counts.works;$('#total-images').textContent=data.counts.images+' 张图 · 随图附来源';$('#updated').textContent='更新于 '+data.updated;
 const cats=[{id:'all',name:'全部画风'},...data.categories];
 $('#categories').innerHTML=cats.map(c=>`<button class="category-button ${c.id==='all'?'active':''}" data-category="${c.id}" aria-pressed="${c.id==='all'}"><span>${esc(c.name)}</span><small>${String(data.works.filter(w=>c.id==='all'||w.category===c.id).length).padStart(2,'0')}</small></button>`).join('');
 const tags=[...new Set(data.works.flatMap(w=>w.tags))];$('#usage').innerHTML+=[...tags].sort((a,b)=>a.localeCompare(b,'zh')).map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');
 function matching(){return data.works.filter(w=>(state.category==='all'||w.category===state.category)&&(state.medium==='all'||w.medium===state.medium)&&(state.usage==='all'||w.tags.includes(state.usage))&&(!state.award||Boolean(w.award))&&(!state.query||[w.name,w.creator,w.summary,...w.tags,categoryName(w.category)].join(' ').toLocaleLowerCase().includes(state.query.toLocaleLowerCase())));}
 function render(){const rows=matching();$('#gallery').innerHTML=rows.map(w=>`<article class="card"><button class="card-button" data-work="${w.id}" aria-label="查看 ${esc(w.name)} 的 ${w.images.length} 张参考图"><div class="cover"><img src="${w.images[0].thumb}" alt="${esc(w.name+' · '+w.images[0].label)}" loading="lazy" width="600" height="450">${w.award?'<span class="badge">Jam '+esc(w.award.badge||'获奖 / 高排名')+'</span>':''}<span class="image-count">${w.images.length} 图</span></div><div class="card-meta"><span>${media[w.medium]}</span><span class="card-index">${esc(w.images[0].id)}</span></div><h3>${esc(w.name)}</h3><p class="card-summary">${esc(w.summary)}</p></button><div class="tags">${w.tags.slice(0,3).map(t=>'<span class="tag">'+esc(t)+'</span>').join('')}</div></article>`).join('');$('#result-count').textContent=rows.length+' 个条目';$('#category-heading').textContent=state.category==='all'?'全部画风':categoryName(state.category);$('#empty').classList.toggle('hidden',rows.length>0);$('#reset').classList.toggle('hidden',Object.entries(state).every(([k,v])=>k==='award'?!v:k==='query'?!v:v==='all'));document.querySelectorAll('[data-category]').forEach(b=>{const yes=b.dataset.category===state.category;b.classList.toggle('active',yes);b.setAttribute('aria-pressed',String(yes))});}
 function reset(){Object.assign(state,{category:'all',medium:'all',usage:'all',query:'',award:false});$('#search').value='';$('#medium').value='all';$('#usage').value='all';$('#award-only').checked=false;render();}
 $('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;state.category=b.dataset.category;render();});
 $('#search').addEventListener('input',e=>{state.query=e.target.value.trim();render()});$('#medium').addEventListener('change',e=>{state.medium=e.target.value;render()});$('#usage').addEventListener('change',e=>{state.usage=e.target.value;render()});$('#award-only').addEventListener('change',e=>{state.award=e.target.checked;render()});$('#reset').addEventListener('click',reset);$('#empty-reset').addEventListener('click',reset);
 function paintImage(){const p=active.images[index];$('#detail-image').src=p.src;$('#detail-image').alt=p.label;$('#image-title').textContent=p.label;$('#image-note').textContent=p.note;$('#image-counter').textContent=(index+1)+' / '+active.images.length;$('#image-source').href=p.source;$('#image-source').textContent=p.provenance?'作品资料（组员供图）':'图片出处';$('#image-original').href=p.original;$('#image-original').textContent=p.archive_member?'查看官方素材包':p.original_is_work_page?'作品官方页面':'查看来源原图';$('#image-quality').textContent=p.width<700?`来源图 ${p.width} × ${p.height}，适合构图概览。`:`来源图 ${p.width} × ${p.height}`;$('#thumbnails').innerHTML=active.images.map((p,i)=>`<button class="thumb ${index===i?'active':''}" data-image-index="${i}" aria-label="查看第 ${i+1} 张：${esc(p.label)}" aria-pressed="${index===i}"><img src="${p.thumb}" alt=""></button>`).join('');$('#previous-image').disabled=active.images.length<2;$('#next-image').disabled=active.images.length<2;}
 function openWork(id,fromHash=false){const w=data.works.find(w=>w.id===id);if(!w)return;active=w;index=0;$('#detail-title').textContent=w.name;$('#detail-meta').textContent=media[w.medium]+' / '+categoryName(w.category);$('#detail-identity').textContent=[w.creator,w.identity].filter(Boolean).join(' · ');$('#detail-summary').textContent=w.summary;$('#detail-tags').innerHTML=w.tags.map(t=>'<span class="tag">'+esc(t)+'</span>').join('');$('#detail-cost').textContent=w.cost;$('#detail-technical').textContent=w.technical||'';$('#work-source').href=w.source;$('#copy-status').textContent='';$('#detail-position').textContent='参考详情 · '+w.images.length+' 张图';const award=$('#award-box');award.classList.toggle('hidden',!w.award);award.innerHTML=w.award?`<strong>${esc(w.award.title)}</strong><p>${esc(w.award.note)}</p><a href="${esc(w.award.source)}" target="_blank" rel="noopener">核对赛事结果</a>`:'';paintImage();if(!$('#detail').open)$('#detail').showModal();$('#detail').scrollTop=0;document.body.style.overflow='hidden';if(!fromHash)history.replaceState(null,'','#work='+encodeURIComponent(id));}
 $('#gallery').addEventListener('click',e=>{const b=e.target.closest('[data-work]');if(b){opener=b;openWork(b.dataset.work)}});
 $('#thumbnails').addEventListener('click',e=>{const b=e.target.closest('[data-image-index]');if(b){index=Number(b.dataset.imageIndex);paintImage()}});
 $('#previous-image').addEventListener('click',()=>{index=(index+active.images.length-1)%active.images.length;paintImage()});$('#next-image').addEventListener('click',()=>{index=(index+1)%active.images.length;paintImage()});
 $('.close-detail').addEventListener('click',()=>$('#detail').close());$('#detail').addEventListener('close',()=>{document.body.style.overflow='';history.replaceState(null,'',location.pathname+location.search);opener?.focus()});
 for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
 $('#copy-link').addEventListener('click',async()=>{const url=new URL(location.href);url.hash='work='+encodeURIComponent(active.id);try{await navigator.clipboard.writeText(url.href);$('#copy-status').textContent='链接已复制，打开即可看到这组参考。'}catch(e){$('#copy-status').textContent='可复制浏览器地址栏中的链接。'}});
 $('#about-open').addEventListener('click',()=>$('#about').showModal());$('#about-close').addEventListener('click',()=>$('#about').close());
 function readHash(){const params=new URLSearchParams(location.hash.slice(1));if(params.has('work'))openWork(params.get('work'),true)}window.addEventListener('hashchange',readHash);render();readHash();
})();
